import Head from "next/head";
import About from "../components/About";
import Hero from "../components/Hero";
import Contacts from "../components/Contacts";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="bg-gray-300">
      <Head>
        <title>My Portfolio Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Contacts />
      {/* <About /> */}
      <Footer />
    </div>
  );
}
